services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    volumes:
      - ../..:/workspaces:cached
    networks:
      - invoiceshelf-dev
    command: sleep infinity

  mysql:
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: invoiceshelf
      MYSQL_DATABASE: invoiceshelf
      MYSQL_USER: invoiceshelf
      MYSQL_PASSWORD: invoiceshelf
    volumes:
      - invoiceshelf-dev-mysql:/var/lib/mysql
    networks:
      - invoiceshelf-dev

  adminer:
    build:
      dockerfile: Dockerfile.adminer
    environment:
      ADMINER_PLUGINS: tables-filter
      ADMINER_DESIGN: konya
    ports:
      - '8081:8081'
    networks:
      - invoiceshelf-dev

  mail:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "8025:8025"
    networks:
      - invoiceshelf-dev

  pdf:
    image: gotenberg/gotenberg:8
    networks:
      - invoiceshelf-dev

networks:
  invoiceshelf-dev:

volumes:
  invoiceshelf-dev-mysql:
